import { ApiHideProperty, ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  IsArray,
  IsBoolean,
  IsInt,
  IsOptional,
  IsString,
  IsUUID,
  ValidateNested,
} from 'class-validator';

export class JobSkillInputDto {
  @ApiPropertyOptional({ description: 'Ordering index in job_skill', example: 0 })
  @IsOptional()
  @IsInt()
  @Type(() => Number)
  index?: number;

  @ApiProperty({
    description: 'Skill id stored in job_skill.skill_id (use Neo4j skill element id/eid)',
    example: '4:abc123:0',
  })
  @IsString()
  skill_id: string;

  @ApiPropertyOptional({ description: 'Skill display name', example: 'TypeScript' })
  @IsOptional()
  @IsString()
  skill_name?: string;
}

export class JobAddressInputDto {
  @ApiPropertyOptional({ description: 'Address line' })
  @IsOptional()
  @IsString()
  address_line?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  no?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  moo?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  soi?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  street?: string;

  @ApiPropertyOptional({ description: 'Sub-district code' })
  @IsOptional()
  @IsInt()
  @Type(() => Number)
  sub_district_code?: number;

  @ApiPropertyOptional({ description: 'District code' })
  @IsOptional()
  @IsInt()
  @Type(() => Number)
  district_code?: number;

  @ApiPropertyOptional({ description: 'Province code' })
  @IsOptional()
  @IsInt()
  @Type(() => Number)
  province_code?: number;

  @ApiPropertyOptional({ description: 'Country code' })
  @IsOptional()
  @IsInt()
  @Type(() => Number)
  country_code?: number;

  @ApiPropertyOptional({ description: 'Postal code row id' })
  @IsOptional()
  @IsInt()
  @Type(() => Number)
  postal_code?: number;
}

export class JobAdditionalQuestionOptionInputDto {
  @ApiProperty({ description: 'Running option number (position in array)', example: 0 })
  @IsInt()
  @Type(() => Number)
  id: number;

  @ApiProperty({ description: 'Option label', example: '34' })
  @IsString()
  label: string;
}

export class JobAdditionalQuestionInputDto {
  @ApiProperty({ description: 'Running question number (position in array)', example: 0 })
  @IsInt()
  @Type(() => Number)
  id: number;

  @ApiProperty({ description: 'Question type', example: 1 })
  @IsInt()
  @Type(() => Number)
  type: number;

  @ApiProperty({ description: 'Question text', example: 'Question For Testing' })
  @IsString()
  question: string;

  @ApiProperty({ description: 'Question options', type: [JobAdditionalQuestionOptionInputDto] })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => JobAdditionalQuestionOptionInputDto)
  options: JobAdditionalQuestionOptionInputDto[];

  @ApiProperty({ description: 'Maximum selectable options', example: 1 })
  @IsInt()
  @Type(() => Number)
  max_select: number;
}

export class JobAdditionalFileInputDto {
  @ApiProperty({ description: 'Running file field number (position in array)', example: 0 })
  @IsInt()
  @Type(() => Number)
  id: number;

  @ApiProperty({ description: 'File field type', example: 1 })
  @IsInt()
  @Type(() => Number)
  type: number;

  @ApiProperty({ description: 'File field label', example: 'Test Upload File' })
  @IsString()
  label: string;

  @ApiProperty({ description: 'File field description', example: 'For Testing Only' })
  @IsString()
  description: string;
}

export class CreateJobDto {
  @ApiPropertyOptional({ description: 'Job id (UUID). If omitted, generated by upstream service.' })
  @IsString()
  @IsUUID()
  @IsOptional()
  id?: string;

  @ApiPropertyOptional({ description: 'Neo4j element id for job (usually generated)' })
  @IsOptional()
  @IsString()
  eid?: string;

  @ApiPropertyOptional({ description: 'Job status (default: 1)', example: 1, default: 1 })
  @IsOptional()
  @IsInt()
  @Type(() => Number)
  status?: number;

  @ApiPropertyOptional({ description: 'Created date (ISO)' })
  @IsOptional()
  @IsString()
  created_at?: string;

  @ApiPropertyOptional({ description: 'Job name', example: 'Software Engineer' })
  @IsOptional()
  @IsString()
  name?: string;

  @ApiPropertyOptional({ description: 'Job description', example: 'We are looking for...' })
  @IsOptional()
  @IsString()
  description?: string;

  @ApiPropertyOptional({ description: 'Job description (RTF)' })
  @IsOptional()
  @IsString()
  description_rtf?: string;

  @ApiPropertyOptional({ description: 'Start apply date (ISO)', example: '2025-03-01' })
  @IsOptional()
  @IsString()
  start_apply?: string;

  @ApiPropertyOptional({ description: 'End apply date (ISO)', example: '2025-03-31' })
  @IsOptional()
  @IsString()
  end_apply?: string;

  @ApiPropertyOptional({ description: 'Require cover letter', example: true })
  @IsOptional()
  @IsBoolean()
  @Type(() => Boolean)
  cover_letter?: boolean;

  @ApiPropertyOptional({ description: 'Require work experience', example: true })
  @IsOptional()
  @IsBoolean()
  @Type(() => Boolean)
  work_experience?: boolean;

  @ApiPropertyOptional({ description: 'Require education', example: true })
  @IsOptional()
  @IsBoolean()
  @Type(() => Boolean)
  education?: boolean;

  @ApiPropertyOptional({
    description: 'Nested address payload for job location fields',
    type: JobAddressInputDto,
  })
  @IsOptional()
  @ValidateNested()
  @Type(() => JobAddressInputDto)
  address?: JobAddressInputDto;

  @ApiPropertyOptional({ description: 'Company id' })
  @IsOptional()
  @IsString()
  company_id?: string;

  @ApiHideProperty()
  @IsOptional()
  @IsString()
  address_line?: string;

  @ApiHideProperty()
  @IsOptional()
  @IsString()
  no?: string;

  @ApiHideProperty()
  @IsOptional()
  @IsString()
  moo?: string;

  @ApiHideProperty()
  @IsOptional()
  @IsString()
  soi?: string;

  @ApiHideProperty()
  @IsOptional()
  @IsString()
  street?: string;

  @ApiHideProperty()
  @IsOptional()
  @IsInt()
  @Type(() => Number)
  sub_district_code?: number;

  @ApiHideProperty()
  @IsOptional()
  @IsInt()
  @Type(() => Number)
  district_code?: number;

  @ApiHideProperty()
  @IsOptional()
  @IsInt()
  @Type(() => Number)
  province_code?: number;

  @ApiHideProperty()
  @IsOptional()
  @IsInt()
  @Type(() => Number)
  country_code?: number;

  @ApiHideProperty()
  @IsOptional()
  @IsInt()
  @Type(() => Number)
  postal_code?: number;

  @ApiPropertyOptional({ description: 'Category ref ids', type: [Number] })
  @IsOptional()
  @IsArray()
  @IsInt({ each: true })
  @Type(() => Number)
  category_ids?: number[];

  @ApiPropertyOptional({ description: 'Work option ref ids', type: [Number] })
  @IsOptional()
  @IsArray()
  @IsInt({ each: true })
  @Type(() => Number)
  work_option_ids?: number[];

  @ApiPropertyOptional({ description: 'Work type ref ids', type: [Number] })
  @IsOptional()
  @IsArray()
  @IsInt({ each: true })
  @Type(() => Number)
  work_type_ids?: number[];

  @ApiPropertyOptional({
    description:
      'Nested skills payload. skill_id will be stored in job_skill and used to connect Neo4j Job->Skill.',
    type: [JobSkillInputDto],
  })
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => JobSkillInputDto)
  skills?: JobSkillInputDto[];

  @ApiHideProperty()
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  skill_ids?: string[];

  @ApiHideProperty()
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  skill_names?: string[];

  @ApiHideProperty()
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  required_skill_element_ids?: string[];

  @ApiHideProperty()
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  skill_element_ids?: string[];

  @ApiPropertyOptional({
    description: 'Additional screening questions shown in application form',
    type: [JobAdditionalQuestionInputDto],
  })
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => JobAdditionalQuestionInputDto)
  addition_questions?: JobAdditionalQuestionInputDto[];

  @ApiPropertyOptional({
    description: 'Additional file upload fields shown in application form',
    type: [JobAdditionalFileInputDto],
  })
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => JobAdditionalFileInputDto)
  addition_file?: JobAdditionalFileInputDto[];
}
